import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar/Navbar.jsx'
import NavbarTwo from '@/components/navbar2.jsx/NavbarTwo';
import { NavbarContextProvider } from '@/context/NavContext/NavbarContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarContextProvider>
          <NavbarTwo />
          {children}
        </NavbarContextProvider>
      </body>
    </html>
  )
}
